diff --git a/extensions/browser/extension_function_histogram_value.h b/extensions/browser/extension_function_histogram_value.h
index 8cb9d5c89164a32cdc53a4f1bfe48b1ea52b7442..0b893cea38e61eedb25382eba2bec01a33092c9d 100644
--- a/extensions/browser/extension_function_histogram_value.h
+++ b/extensions/browser/extension_function_histogram_value.h
@@ -2040,6 +2040,34 @@ enum HistogramValue {
   CONTEXTUALTASKSPRIVATE_LAUNCHPANELINNEWTAB = 1975,
   DICTATIONPRIVATE_UPDATETRANSCRIPTION = 1976,
   DICTATIONPRIVATE_SETSTREAMSTATE = 1977,
+  // BrowserOS: extension function histogram values
+  DELETED_BROWSER_OS_GETACCESSIBILITYTREE = 1978,
+  DELETED_BROWSER_OS_GETINTERACTIVESNAPSHOT = 1979,
+  DELETED_BROWSER_OS_CLICK = 1980,
+  DELETED_BROWSER_OS_INPUTTEXT = 1981,
+  DELETED_BROWSER_OS_CLEAR = 1982,
+  DELETED_BROWSER_OS_GETPAGELOADSTATUS = 1983,
+  DELETED_BROWSER_OS_SCROLLUP = 1984,
+  DELETED_BROWSER_OS_SCROLLDOWN = 1985,
+  DELETED_BROWSER_OS_SCROLLTONODE = 1986,
+  DELETED_BROWSER_OS_SENDKEYS = 1987,
+  DELETED_BROWSER_OS_GETPAGESTRUCTURE = 1988,
+  DELETED_BROWSER_OS_CAPTURESCREENSHOT = 1989,
+  DELETED_BROWSER_OS_GETSNAPSHOT = 1990,
+  BROWSER_OS_GETPREF = 1991,
+  BROWSER_OS_SETPREF = 1992,
+  DELETED_BROWSER_OS_GETALLPREFS = 1993,
+  BROWSER_OS_LOGMETRIC = 1994,
+  BROWSER_OS_GETVERSIONNUMBER = 1995,
+  DELETED_BROWSER_OS_EXECUTEJAVASCRIPT = 1996,
+  DELETED_BROWSER_OS_CLICKCOORDINATES = 1997,
+  DELETED_BROWSER_OS_TYPEATCOORDINATES = 1998,
+  SIDEPANEL_BROWSEROSTOGGLE = 1999,
+  SIDEPANEL_BROWSEROSISOPEN = 2000,
+  BROWSER_OS_GETBROWSEROSVERSIONNUMBER = 2001,
+  BROWSER_OS_CHOOSEPATH = 2002,
+  BROWSER_OS_SHOWTOAST = 2003,
+  BROWSER_OS_SHOWINFOBAR = 2004,
   // Last entry: Add new entries above, then run:
   // tools/metrics/histograms/update_extension_histograms.py
   ENUM_BOUNDARY
