import { ENV_REGISTRY, type EnvMode, type EnvSection } from './registry'

const SECTION_ORDER: readonly EnvSection[] = [
  'dev-tools',
  'app',
  'claw',
  'server',
  'build',
  'upload',
  'sign',
]

/** Generates the root env example text from the ordered registry. */
export function generateEnvExample(mode: EnvMode): string {
  const lines = [
    '# Generated by bun run env:examples. Do not edit by hand.',
    `# This is the ${mode} env example for the BrowserOS monorepo root.`,
    `# Copy it to .env.${mode}; real .env.${mode} files are gitignored.`,
  ]

  for (const section of SECTION_ORDER) {
    const specs = ENV_REGISTRY.filter(
      (spec) => spec.section === section && spec.modes[mode],
    )
    if (specs.length === 0) {
      continue
    }

    lines.push('', `# --- ${section} ---`)

    for (const spec of specs) {
      const entry = spec.modes[mode]
      if (!entry) {
        continue
      }

      lines.push('')
      for (const descriptionLine of spec.description.split('\n')) {
        lines.push(`# ${descriptionLine}`)
      }

      const assignment = `${spec.key}=${entry.value}`
      lines.push(entry.commented ? `# ${assignment}` : assignment)
    }
  }

  return `${lines.join('\n')}\n`
}
